{
 "title": "Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network traffic OUT (Mbit/s)  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "  rate(node_network_transmit_bytes_total{instance=\"$instance\",device=~\"(eth|en).*\"}[5m]) * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic IN (Mbit/s)  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "  rate(node_network_receive_bytes_total{instance=\"$instance\",device=~\"(eth|en).*\"}[5m]) * 8 / 1000000\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk write (B/s)  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "  rate(node_disk_written_bytes_total{instance=\"$instance\"}[5m])\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read (B/s)  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "  rate(node_disk_read_bytes_total{instance=\"$instance\"}[5m])\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free disk space (GB, root)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  node_filesystem_free_bytes{instance=\"$instance\",mountpoint=\"/\"} / 1024 / 1024 / 1024\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM used (GB) ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  (node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemAvailable_bytes{instance=\"$instance\"}) / 1024 / 1024 / 1024\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM used %  ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  100 - (node_memory_MemAvailable_bytes{instance=\"$instance\"} / node_memory_MemTotal_bytes{instance=\"$instance\"} * 100)\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load 5 minutes ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load 1 minute  ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  node_load1{instance=\"$instance\"}\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % per core (for Heatmap)  ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "  100 - (avg by (cpu) (rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$instance\"}[5m])) * 100)\n  ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}